In [158]:
import numpy as np

## task 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [159]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## task 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [160]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [161]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

a3 = a.reshape(4, 3)
a3

In [162]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [163]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

## task 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [164]:
b1 = a.reshape(2, -1)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [165]:
b2 = a.reshape(3, -1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [166]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [167]:
b4 = a.reshape(-1, 2)
b4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [168]:
b5 = a.reshape(-1, 3)
b5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## task 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [169]:
a5.ndim

2

## task 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [170]:
c = np.random.randn(3, 4)
c1 = c.flatten()
c1.ndim

1

In [171]:
c.size == c1.size

True

## task 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [172]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## task 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [173]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [174]:
a.ndim == b.ndim

False

## task 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [175]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [176]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [177]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [178]:
v.size

10

## task 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [179]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [180]:
At = A.T

In [181]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [182]:
B.shape

(4, 4)

In [183]:
np.linalg.det(B)

0.0

## task 10-11

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [184]:
np.random.seed(42)
c = np.rint(np.random.sample(16)*16)
c = c.astype(int)
c

array([ 6, 15, 12, 10,  2,  2,  1, 14, 10, 11,  0, 16, 13,  3,  3,  3])

## task 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [185]:
C = c.reshape(4, 4)
C

array([[ 6, 15, 12, 10],
       [ 2,  2,  1, 14],
       [10, 11,  0, 16],
       [13,  3,  3,  3]])

In [186]:
D = B + C*10
D

array([[ 65, 164, 143, 132],
       [ 34,  70,  96, 262],
       [123, 196, 149, 372],
       [162, 152, 242, 332]])

In [187]:
D_det = np.linalg.det(D)
D_det

-284231999.9999997

In [188]:
D_rank = np.linalg.matrix_rank(D)
D_rank

4

In [189]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.00997706, -0.01618115,  0.00875975,  0.00692111],
       [ 0.00689831, -0.00311351,  0.00506262, -0.00595823],
       [ 0.00622998,  0.00709674, -0.01131794,  0.00460413],
       [-0.00283107,  0.00414816,  0.00165766, -0.00099327]])

In [190]:
D.dot(D_inv)

array([[ 1.00000000e+00, -9.02056208e-17,  0.00000000e+00,
         0.00000000e+00],
       [-5.55111512e-17,  1.00000000e+00,  1.11022302e-16,
         0.00000000e+00],
       [-5.55111512e-17,  0.00000000e+00,  1.00000000e+00,
         2.22044605e-16],
       [-1.38777878e-17, -1.11022302e-16,  0.00000000e+00,
         1.00000000e+00]])

## task 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [191]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 1., 1.],
       [1., 0., 1., 0.],
       [1., 1., 0., 1.],
       [0., 1., 1., 0.]])

In [192]:
E = np.where(D_inv == 1, B, C)
E

array([[  6,  15,  23,  32],
       [ 14,   2,  86,  14],
       [ 23,  86,   0, 212],
       [ 13, 122, 212,   3]])